// Auto-generated portfolio data
// This file is generated by scripts/generate-portfolio-data.js
// Do not edit manually

export interface Artwork {
    id: string;
    title: string;
    year?: string;
    image: string;
    description?: string;
}

export interface Category {
    name: string;
    displayName: string;
    artworks: Artwork[];
}

// Portfolio categories data
export const portfolioCategories: string[] = [
  "fiber art",
  "garments",
  "graphics",
  "illustration",
  "test12"
];

// Display name mapping
export const displayNameMap: Record<string, string> = {
    'fiber art': 'Fiber Art',
    'garments': 'Garments',
    'graphics': 'Graphics',
    'illustration': 'Illustration',
    'test12': 'Test12'
};

// Pre-generated artwork data for each category
export const categoryArtworks: Record<string, Artwork[]> = {
  "fiber art": [
    {
      "id": "fiber art-1",
      "title": "3f238ad0 6a32 4771 9b09 54157dcf7167",
      "image": "fiber art/3F238AD0-6A32-4771-9B09-54157DCF7167.jpg"
    },
    {
      "id": "fiber art-2",
      "title": "7457e178 F871 4b87 9545 Adb7f5b7fc7d",
      "image": "fiber art/7457E178-F871-4B87-9545-ADB7F5B7FC7D.jpg"
    },
    {
      "id": "fiber art-3",
      "title": "84323b5e 3165 46be Bf32 490735354672",
      "image": "fiber art/84323B5E-3165-46BE-BF32-490735354672.jpg"
    },
    {
      "id": "fiber art-4",
      "title": "C526a88f 8752 491e B1a4 5f06927d5ecf",
      "image": "fiber art/C526A88F-8752-491E-B1A4-5F06927D5ECF.jpg"
    },
    {
      "id": "fiber art-5",
      "title": "F2386188 67ae 4240 Ac3e D2ef96bb5060",
      "image": "fiber art/F2386188-67AE-4240-AC3E-D2EF96BB5060.jpg"
    }
  ],
  "garments": [
    {
      "id": "garments-1",
      "title": "Backcard",
      "image": "garments/BACKCARD.png"
    },
    {
      "id": "garments-2",
      "title": "Gun",
      "image": "garments/GUN.png"
    },
    {
      "id": "garments-3",
      "title": "Gun2",
      "image": "garments/GUN2.png"
    },
    {
      "id": "garments-4",
      "title": "Gun3",
      "image": "garments/GUN3.png"
    },
    {
      "id": "garments-5",
      "title": "Img 8285",
      "image": "garments/IMG_8285.png"
    },
    {
      "id": "garments-6",
      "title": "Img 8302",
      "image": "garments/IMG_8302.png"
    },
    {
      "id": "garments-7",
      "title": "Img 8304",
      "image": "garments/IMG_8304.png"
    },
    {
      "id": "garments-8",
      "title": "Kingdom",
      "image": "garments/KINGDOM.png"
    },
    {
      "id": "garments-9",
      "title": "Ranger",
      "image": "garments/Ranger.png"
    },
    {
      "id": "garments-10",
      "title": "Ranger1",
      "image": "garments/Ranger1.png"
    },
    {
      "id": "garments-11",
      "title": "Ranger2",
      "image": "garments/Ranger2.png"
    },
    {
      "id": "garments-12",
      "title": "Ranger3",
      "image": "garments/Ranger3.png"
    },
    {
      "id": "garments-13",
      "title": "Soldierred",
      "image": "garments/SoldierRED.png"
    },
    {
      "id": "garments-14",
      "title": "Untitled 1",
      "image": "garments/Untitled-1.jpg"
    }
  ],
  "graphics": [
    {
      "id": "graphics-1",
      "title": "4ashion",
      "image": "graphics/4ashion.png"
    },
    {
      "id": "graphics-2",
      "title": "4unky7ounds",
      "image": "graphics/4unky7ounds.png"
    },
    {
      "id": "graphics-3",
      "title": "Book",
      "image": "graphics/Book.png"
    },
    {
      "id": "graphics-4",
      "title": "Downtownstonestorewide",
      "image": "graphics/DowntownStoneStoreWIDE.png"
    },
    {
      "id": "graphics-5",
      "title": "Img 8302",
      "image": "graphics/IMG_8302.png"
    },
    {
      "id": "graphics-6",
      "title": "Screenshot 2025 09 07 201605",
      "image": "graphics/Screenshot 2025-09-07 201605.png"
    },
    {
      "id": "graphics-7",
      "title": "Screenshot 2025 09 07 201901",
      "image": "graphics/Screenshot 2025-09-07 201901.png"
    },
    {
      "id": "graphics-8",
      "title": "Screenshot 2025 09 07 202204",
      "image": "graphics/Screenshot 2025-09-07 202204.png"
    },
    {
      "id": "graphics-9",
      "title": "Screenshot 2025 09 07 202307",
      "image": "graphics/Screenshot 2025-09-07 202307.png"
    },
    {
      "id": "graphics-10",
      "title": "Screenshot 2025 09 07 202330",
      "image": "graphics/Screenshot 2025-09-07 202330.png"
    },
    {
      "id": "graphics-11",
      "title": "Screenshot 2025 09 07 202440",
      "image": "graphics/Screenshot 2025-09-07 202440.png"
    },
    {
      "id": "graphics-12",
      "title": "Screenshot 2025 09 07 202802",
      "image": "graphics/Screenshot 2025-09-07 202802.png"
    },
    {
      "id": "graphics-13",
      "title": "Screenshot 2025 09 07 203354",
      "image": "graphics/Screenshot 2025-09-07 203354.png"
    },
    {
      "id": "graphics-14",
      "title": "Screenshot 2025 09 07 203715",
      "image": "graphics/Screenshot 2025-09-07 203715.png"
    },
    {
      "id": "graphics-15",
      "title": "Screenshot 2025 09 07 204113",
      "image": "graphics/Screenshot 2025-09-07 204113.png"
    },
    {
      "id": "graphics-16",
      "title": "Screenshot 2025 09 07 204216",
      "image": "graphics/Screenshot 2025-09-07 204216.png"
    },
    {
      "id": "graphics-17",
      "title": "Screenshot 2025 09 07 204319",
      "image": "graphics/Screenshot 2025-09-07 204319.png"
    },
    {
      "id": "graphics-18",
      "title": "Screenshot 2025 09 07 204732",
      "image": "graphics/Screenshot 2025-09-07 204732.png"
    },
    {
      "id": "graphics-19",
      "title": "Screenshot 2025 09 07 204859",
      "image": "graphics/Screenshot 2025-09-07 204859.png"
    },
    {
      "id": "graphics-20",
      "title": "Screenshot 2025 09 07 204947",
      "image": "graphics/Screenshot 2025-09-07 204947.png"
    },
    {
      "id": "graphics-21",
      "title": "Screenshot 2025 09 07 210124",
      "image": "graphics/Screenshot 2025-09-07 210124.png"
    },
    {
      "id": "graphics-22",
      "title": "Screenshot 2025 09 07 210218",
      "image": "graphics/Screenshot 2025-09-07 210218.png"
    }
  ],
  "illustration": [
    {
      "id": "illustration-1",
      "title": "Arena2.0005",
      "image": "illustration/Arena2.0005.jpg"
    },
    {
      "id": "illustration-2",
      "title": "Haters",
      "image": "illustration/Haters.jpg"
    },
    {
      "id": "illustration-3",
      "title": "Haters15",
      "image": "illustration/Haters15.jpg"
    },
    {
      "id": "illustration-4",
      "title": "Img 8305",
      "image": "illustration/IMG_8305.png"
    },
    {
      "id": "illustration-5",
      "title": "Leafy.0060",
      "image": "illustration/leafy.0060.jpg"
    },
    {
      "id": "illustration-6",
      "title": "Leafy.0061",
      "image": "illustration/leafy.0061.jpg"
    },
    {
      "id": "illustration-7",
      "title": "Versus2.0014",
      "image": "illustration/Versus2.0014.jpg"
    }
  ],
  "test12": [
    {
      "id": "test12-1",
      "title": "Arena2.0005",
      "image": "test12/Arena2.0005.jpg"
    }
  ]
};

// Function to get display name for a category
export function getDisplayName(categoryName: string): string {
    return displayNameMap[categoryName] || categoryName.charAt(0).toUpperCase() + categoryName.slice(1);
}

// Function to generate title from filename
export function generateTitleFromFileName(fileName: string): string {
    const nameWithoutExt = fileName.replace(/\.[^/.]+$/, '');
    return nameWithoutExt
        .split(/[-_]/)
        .map(word => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
        .join(' ');
}

// Function to get artworks for a category
export function scanCategoryArtworks(categoryName: string): Artwork[] {
    return categoryArtworks[categoryName] || [];
}
